// ACTION TYPES
export const DAOS_LIST_START = 'DAOS_LIST_START';
export const DAOS_LIST_SUCCESS = 'DAOS_LIST_SUCCESS';
export const DAOS_LIST_FAILURE = 'DAOS_LIST_FAILURE';
export const DAOS_LIST_RESET = 'DAOS_LIST_RESET';
export const DAOS_LIST_FILTER = 'DAOS_LIST_FILTER';

// STATUS TYPES
export const DAOS_LIST_STATUS_PENDING = 'DAOS_LIST_STATUS_PENDING';
export const DAOS_LIST_STATUS_RESOLVED = 'DAOS_LIST_STATUS_RESOLVED';
export const DAOS_LIST_STATUS_REJECTED = 'DAOS_LIST_STATUS_REJECTED';
